# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Abear
author: abearxiong
email: xiongxiao1012@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
   每一天都是一个新的开始，今天与明天最大的不同，今天我还活着，明天却毫无感觉。所以时刻注重今天的美好时光，热爱生活，热爱创造。
baseurl: "/" # the subpath of your site, e.g. /blog
url: https://abearxiong.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: abear02789740
github_username:  abearxiong
locale: zh-Cn

# Build settings
markdown: kramdown
bearlife:
        theme: bearlife
version: 1.0
#timezone: TIMEZONE
timezone: Asia/Shanghai
#timezone: '+8000'
excerpt_separator:  '<!-- more -->'
permalink: /:categories/:year/:month/:title.html
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-archives
  - jekyll-redirect-from
  - jemoji
kramdown:
        input: GFM
sass:
        sass_dir: _sass 
        style: compressed
comment:
        disqus: abearxiong 

# There is for disqus setting
disqus:
        shortname: abearxiong
google_analytics: 'UA-143586782-1'
# There is for paginate
paginate: 10
paginate_path: "page:num"
gist:
  noscript: false
# There is for jekyll compoesr
# 自动打开编辑器
# The creation timestamp under the date attribure.
# The title attribute under the title attribute
# 发布的语法
# jekyll_compose:
# #   auto_open: true
#   default_front_matter:
#     drafts:
#       description:
#       image:
#       category:
#       tags: ["think"]
#     posts:
#       description: "秒速"
#       image:
#       category:
#       tags: 
#       published: false
#       sitemap: false
jekyll_compose:
  auto_open: true
  draft_default_front_matter:
    category:
    tags:
    image:
    description:
  post_default_front_matter:
    category:
    tags:
    image:
    description:
    published: false
    sitemap: false
jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - rakefile
  - ShellPython/
  - ShellRb/
  - jekyllServer.sh
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
