# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Abear
email: xiongxiao1012@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
   每一天都是一个新的开始，今天与明天最大的不同，今天我还活着，明天却毫无感觉。所以时刻注重今天的美好时光，写好代码，玩好，IT男。
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://abearxiong.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: abear02789740
github_username:  abearxiong

# Build settings
markdown: kramdown
#theme: minima
#timezone: TIMEZONE
timezone: Asia/Shanghai
#timezone: '+8000'
excerpt_separator:  '<!-- more -->'
permalink: /:categories/:year/:month/:title.html
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
kramdown:
        input: GFM
sass:
        sass_dir: _sass 
        style: compressed
comment:
        disqus: abearxiong 

# There is for disqus setting
disqus:
        shortname: abearxiong
# There is for paginate
paginate: 3
paginate_path: "page:num"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - con.sh
  - rakefile
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
